// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"name":"不展示全局布局","layout":false,"id":"1"},"2":{"path":"/*","parentId":"1","id":"2"},"3":{"path":"/500","parentId":"1","id":"3"},"4":{"path":"/","redirect":"/home","parentId":"@@/global-layout","id":"4"},"5":{"name":"首页","path":"/home","parentId":"@@/global-layout","id":"5"},"6":{"name":"权限演示","path":"/access","parentId":"@@/global-layout","id":"6"},"7":{"name":" CRUD 示例","path":"/table","parentId":"@@/global-layout","id":"7"},"@@/global-layout":{"id":"@@/global-layout","path":"/","parentId":"ant-design-pro-layout","isLayout":true},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__StatusPages__404" */'@/pages/StatusPages/404.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__StatusPages__500" */'@/pages/StatusPages/500.tsx')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Access__index" */'@/pages/Access/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Table__index" */'@/pages/Table/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/zcy/Desktop/frontend-cli/src/layouts/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/zcy/Desktop/frontend-cli/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
