// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps.js';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"StatusPages/404":{"path":"StatusPages/404","id":"StatusPages/404","parentId":"@@/global-layout"},"StatusPages/500":{"path":"StatusPages/500","id":"StatusPages/500","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'StatusPages/404': React.lazy(() => import(/* webpackChunkName: "src__pages__StatusPages__404" */'../../../src/pages/StatusPages/404.tsx')),
'StatusPages/500': React.lazy(() => import(/* webpackChunkName: "src__pages__StatusPages__500" */'../../../src/pages/StatusPages/500.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/zcy/Desktop/frontend-cli/src/layouts/index.tsx')),
},
  };
}
